packages:
  - "packages/*"
  - docs

catalog:
  "@types/node": ^22.0.0
  zod: ^4.1.4
  unbuild: ^3.6.0
  vitest: ^3.2.4
  typescript: ^5.3.0

catalogs:
  dev-db-adapters:
    "@electric-sql/pglite": ^0.3.7
    "@prisma/client": ^5.0.0
    "@types/pg": ^8.15.5
    "drizzle-orm": ^0.44.4
    "drizzle-kit": ^0.31.4
    "prisma": ^5.0.0
